Repository Jagannath-Developer/ksoft-solution, pull requests merged in 2024-02, with the labels that each got.

#1 installed setup for react
  frontend_react/package.json
  frontend_react/src/App.css
  frontend_react/src/App.tsx
  frontend_react/src/containers/auth/__test__/index.test.ts
  frontend_react/src/containers/auth/index.module.scss
  frontend_react/src/containers/auth/index.tsx
  frontend_react/src/index.css
  frontend_react/src/index.tsx
  frontend_react/src/logo.svg
  frontend_react/src/setupTests.ts
  frontend_react/tsconfig.json
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: enhancement

#2 added packages for frontend
  .env
  backend_nest/package.json
  frontend_react/package.json
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: documentation, enhancement

#3 added font and login screen UI
  .gitignore
  frontend_react/libs.txt
  frontend_react/package.json
  frontend_react/src/App.tsx
  frontend_react/src/assets/fonts/Poppins/OFL.txt
  frontend_react/src/assets/fonts/Poppins/Poppins-Black.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-BlackItalic.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-Bold.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-BoldItalic.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-ExtraBold.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-ExtraLight.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-Italic.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-Light.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-LightItalic.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-Medium.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-MediumItalic.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-Regular.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-SemiBold.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-Thin.ttf
  frontend_react/src/assets/fonts/Poppins/Poppins-ThinItalic.ttf
  frontend_react/src/assets/styles/font.scss
  frontend_react/src/assets/styles/global.scss
  frontend_react/src/containers/auth/index.module.scss
  frontend_react/src/containers/auth/index.tsx
  frontend_react/src/index.css
  frontend_react/src/index.tsx
  frontend_react/tailwind.config.js
  frontend_react/tsconfig.json
Labels: enhancement

#5 Ashok works
  .vscode/settings.json
  frontend_react/package.json
  frontend_react/src/App.test.tsx
  frontend_react/src/assets/styles/_font.scss
  frontend_react/src/assets/styles/_mixins.scss
  frontend_react/src/assets/styles/global.scss
  frontend_react/src/components/__test__/_button/__snapshots__/button.snapshot.test.tsx.snap
  frontend_react/src/components/__test__/_button/button.snapshot.test.tsx
  frontend_react/src/components/__test__/_button/button.spec.tsx
  frontend_react/src/components/button/index.tsx
  frontend_react/src/components/index.ts
  frontend_react/src/components/modal/index.tsx
  frontend_react/src/config/api.ts
  frontend_react/src/containers/auth/__test__/index.test.ts
  frontend_react/src/setupTests.ts
Labels: documentation, enhancement

#7 Jitu works
  frontend_react/package.json
  frontend_react/src/App.tsx
  frontend_react/src/components/button/index.tsx
  frontend_react/src/components/modal/index.tsx
  frontend_react/src/containers/auth/constant.ts
  frontend_react/src/containers/auth/index.module.scss
  frontend_react/src/containers/auth/index.tsx
  frontend_react/src/containers/auth/redux/selectors.ts
  frontend_react/src/containers/auth/redux/services.ts
  frontend_react/src/containers/navbar/constant.ts
  frontend_react/src/containers/navbar/index.tsx
  frontend_react/src/context/features/authSlice.ts
  frontend_react/src/context/store/index.ts
  frontend_react/src/index.tsx
Labels: enhancement

#8 UI developers
  .vscode/settings.json
  frontend_react/package.json
  frontend_react/src/App.test.tsx
  frontend_react/src/App.tsx
  frontend_react/src/assets/styles/_font.scss
  frontend_react/src/assets/styles/_mixins.scss
  frontend_react/src/assets/styles/global.scss
  frontend_react/src/components/__test__/_button/__snapshots__/button.snapshot.test.tsx.snap
  frontend_react/src/components/__test__/_button/button.snapshot.test.tsx
  frontend_react/src/components/__test__/_button/button.spec.tsx
  frontend_react/src/components/button/index.tsx
  frontend_react/src/components/index.ts
  frontend_react/src/components/modal/index.tsx
  frontend_react/src/config/api.ts
  frontend_react/src/containers/auth/__test__/index.test.ts
  frontend_react/src/containers/auth/constant.ts
  frontend_react/src/containers/auth/index.module.scss
  frontend_react/src/containers/auth/index.tsx
  frontend_react/src/containers/auth/redux/selectors.ts
  frontend_react/src/containers/auth/redux/services.ts
  frontend_react/src/containers/navbar/constant.ts
  frontend_react/src/containers/navbar/index.tsx
  frontend_react/src/context/features/authSlice.ts
  frontend_react/src/context/store/index.ts
  frontend_react/src/index.tsx
  frontend_react/src/setupTests.ts
Labels: documentation, enhancement

#9 navbar component UI reponsive for mobile in progress
  frontend_react/package.json
  frontend_react/src/App.tsx
  frontend_react/src/components/index.ts
  frontend_react/src/components/navbar/constant.ts
  frontend_react/src/components/navbar/index.tsx
  frontend_react/src/containers/auth/index.tsx
  frontend_react/src/containers/auth/redux/selectors.ts
  frontend_react/src/containers/navbar/constant.ts
  frontend_react/src/containers/navbar/index.tsx
Labels: enhancement

#11 nest api setup -- swagger,mongodb
  backend_nest/.env
  backend_nest/nest-cli.json
  backend_nest/package.json
  backend_nest/src/app.controller.spec.ts
  backend_nest/src/app.controller.ts
  backend_nest/src/app.module.ts
  backend_nest/src/app/app.module.ts
  backend_nest/src/app/controllers/app.controller.ts
  backend_nest/src/app/services/app.service.ts
  backend_nest/src/auth/auth.module.ts
  backend_nest/src/auth/auth/auth.controller.spec.ts
  backend_nest/src/auth/auth/auth.controller.ts
  backend_nest/src/auth/auth/auth.service.spec.ts
  backend_nest/src/auth/auth/auth.service.ts
  backend_nest/src/auth/dto/auth.dto/auth.dto.spec.ts
  backend_nest/src/auth/dto/auth.dto/auth.dto.ts
  backend_nest/src/auth/entity/auth.entity/auth.entity.spec.ts
  backend_nest/src/auth/entity/auth.entity/auth.entity.ts
  backend_nest/src/main.ts
  backend_nest/src/swagger.ts
  backend_nest/src/utils/config.ts
Labels: documentation, enhancement

#14 nest api setup
  backend_nest/src/app.controller.spec.ts
  backend_nest/src/app.controller.ts
  backend_nest/src/app.module.ts
  backend_nest/src/app/app.module.ts
  backend_nest/src/app/controllers/app.controller.ts
  backend_nest/src/app/services/app.service.ts
  backend_nest/src/auth/auth.module.ts
  backend_nest/src/auth/auth/auth.controller.spec.ts
  backend_nest/src/auth/auth/auth.controller.ts
  backend_nest/src/auth/auth/auth.service.spec.ts
  backend_nest/src/auth/auth/auth.service.ts
  backend_nest/src/auth/dto/auth.dto/auth.dto.spec.ts
  backend_nest/src/auth/dto/auth.dto/auth.dto.ts
  backend_nest/src/auth/entity/auth.entity/auth.entity.spec.ts
  backend_nest/src/auth/entity/auth.entity/auth.entity.ts
  backend_nest/src/main.ts
  backend_nest/src/swagger.ts
  backend_nest/src/utils/config.ts
Labels: documentation, help wanted, feature
